## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLK]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]
 
## Switches
set_property PACKAGE_PIN V17 [get_ports {SWITCHES[0]}]		
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[0]}]
set_property PACKAGE_PIN V16 [get_ports {SWITCHES[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[1]}]
set_property PACKAGE_PIN W16 [get_ports {SWITCHES[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[2]}]
set_property PACKAGE_PIN W17 [get_ports {SWITCHES[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[3]}]
set_property PACKAGE_PIN W15 [get_ports {SWITCHES[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[4]}]
set_property PACKAGE_PIN V15 [get_ports {SWITCHES[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[5]}]
set_property PACKAGE_PIN W14 [get_ports {SWITCHES[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[6]}]
set_property PACKAGE_PIN W13 [get_ports {SWITCHES[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[7]}]
 

## LEDs
set_property PACKAGE_PIN U16 [get_ports {LEDS[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDS[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDS[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDS[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDS[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDS[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[5]}]
set_property PACKAGE_PIN U14 [get_ports {LEDS[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[6]}]
set_property PACKAGE_PIN V14 [get_ports {LEDS[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[7]}]

	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {CATHODES[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CATHODES[6]}]
set_property PACKAGE_PIN W6 [get_ports {CATHODES[5]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {CATHODES[5]}]
set_property PACKAGE_PIN U8 [get_ports {CATHODES[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CATHODES[4]}]
set_property PACKAGE_PIN V8 [get_ports {CATHODES[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CATHODES[3]}]
set_property PACKAGE_PIN U5 [get_ports {CATHODES[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CATHODES[2]}]
set_property PACKAGE_PIN V5 [get_ports {CATHODES[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CATHODES[1]}]
set_property PACKAGE_PIN U7 [get_ports {CATHODES[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CATHODES[0]}]

set_property PACKAGE_PIN V7 [get_ports CATHODES[7]]							
	set_property IOSTANDARD LVCMOS33 [get_ports CATHODES[7]]

set_property PACKAGE_PIN U2 [get_ports {ANODES[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[0]}]
set_property PACKAGE_PIN U4 [get_ports {ANODES[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[1]}]
set_property PACKAGE_PIN V4 [get_ports {ANODES[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[2]}]
set_property PACKAGE_PIN W4 [get_ports {ANODES[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[3]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports BTNC]						
	set_property IOSTANDARD LVCMOS33 [get_ports BTNC]
#set_property PACKAGE_PIN T18 [get_ports ]						
	#set_property IOSTANDARD LVCMOS33 [get_ports BTNI]
set_property PACKAGE_PIN W19 [get_ports BTNL]						
	set_property IOSTANDARD LVCMOS33 [get_ports BTNL]
#set_property PACKAGE_PIN T17 [get_ports btnR]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnR]
#set_property PACKAGE_PIN U17 [get_ports btnD]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnD]
 

##VGA Connector
    set_property PACKAGE_PIN G19 [get_ports {VGA_RGB[5]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[5]}]
    set_property PACKAGE_PIN H19 [get_ports {VGA_RGB[5]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[5]}]
    set_property PACKAGE_PIN J19 [get_ports {VGA_RGB[6]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[6]}]
    set_property PACKAGE_PIN N19 [get_ports {VGA_RGB[7]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[7]}]
    set_property PACKAGE_PIN N18 [get_ports {VGA_RGB[0]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[0]}]
    set_property PACKAGE_PIN L18 [get_ports {VGA_RGB[0]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[0]}]
    set_property PACKAGE_PIN K18 [get_ports {VGA_RGB[1]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[1]}]
    set_property PACKAGE_PIN J18 [get_ports {VGA_RGB[1]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[1]}]
    set_property PACKAGE_PIN J17 [get_ports {VGA_RGB[2]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[2]}]
    set_property PACKAGE_PIN H17 [get_ports {VGA_RGB[2]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[2]}]
    set_property PACKAGE_PIN G17 [get_ports {VGA_RGB[3]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[3]}]
    set_property PACKAGE_PIN D17 [get_ports {VGA_RGB[4]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RGB[4]}]
    set_property PACKAGE_PIN P19 [get_ports VGA_HS]
        set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
    set_property PACKAGE_PIN R19 [get_ports VGA_VS]
        set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]

##USB HID (PS/2) 
    set_property PACKAGE_PIN C17 [get_ports PS2CLK] 
        set_property IOSTANDARD LVCMOS33 [get_ports PS2CLK] 
    set_property PULLUP true [get_ports PS2CLK] 
        set_property PACKAGE_PIN B17 [get_ports PS2DATA] 
    set_property IOSTANDARD LVCMOS33 [get_ports PS2DATA] 
        set_property PULLUP true [get_ports PS2DATA]